# SERVICE: SAGE Role-Specific Department Capabilities
# Converts configurable department names + staff positions into unique workspaces, job tools, KPIs and role focus while keeping permissions separate from job presentation.

DEFAULT = {"title": "Department Operations", "icon": "briefcase", "description": "Track requests, departmental items, evidence and accountable day-to-day activity.", "roles": ["Department Head", "Officer", "Assistant"], "actions": ["Create requests", "Track department spend", "Upload supporting documents", "View department reports"], "kpis": ["Spend vs budget", "Pending approvals", "Evidence compliance", "Department activity"], "tools": [{"label": "New Request", "detail": "Request an item, service or operational need.", "icon": "requests", "action": "request"}, {"label": "Department Catalogue", "detail": "Browse suggested items and add custom items.", "icon": "inventory", "route": "catalog"}, {"label": "My Reports", "detail": "Review your accountable activity and records.", "icon": "reports", "route": "reports"}]}

PROFILES = [
    ({"finance", "account", "treasury", "cashier", "billing"}, {"title":"Finance & Accounts","icon":"finance","description":"Control financial records, reconciliations, budgets, receivables/payables and evidence.","roles":["Finance Manager / CFO","Accountant","Accounts Officer","Cashier","Auditor"],"actions":["Record income / revenue","Post expenses / expenditure","Track receivables / payables","Reconcile cash, POS and bank","Manage budgets, payroll and taxes"],"kpis":["Income","Expenditure","Cash flow","AR/AP aging","Profit / loss"],"tools":[{"label":"Finance Control","detail":"Post and review authorized financial records.","icon":"finance","route":"finance"},{"label":"Requests","detail":"Raise and follow financial or operating requests.","icon":"requests","route":"requests"},{"label":"Finance Item Catalogue","detail":"Finance devices, records, forms and secure equipment.","icon":"document","route":"catalog"},{"label":"Reports","detail":"Review finance and accountability reports.","icon":"reports","route":"reports"}]}),
    ({"procurement", "purchasing", "buyer"}, {"title":"Procurement & Purchasing","icon":"cart","description":"Turn approved needs into controlled supplier sourcing, purchases and delivery evidence.","roles":["Procurement Manager","Procurement Officer","Buyer","Purchasing Officer"],"actions":["Create sourcing requests","Compare quotations","Create purchase orders","Track supplier commitments","Confirm delivery status"],"kpis":["Committed spend","Purchase-price variance","Supplier performance","Approval turnaround","Emergency buys"],"tools":[{"label":"Procurement Hub","detail":"Track approved needs and purchase activity.","icon":"cart","route":"procurement"},{"label":"New Request","detail":"Raise a new purchase or service requirement.","icon":"requests","action":"request"},{"label":"Procurement Catalogue","detail":"Browse procurement tools, forms and equipment.","icon":"document","route":"catalog"},{"label":"Inventory","detail":"Review received stock and quantities.","icon":"inventory","route":"inventory"}]}),
    ({"store", "inventory", "warehouse"}, {"title":"Stores & Inventory","icon":"inventory","description":"Control stock custody, receiving, issue, replenishment and accountable inventory value.","roles":["Inventory Manager","Storekeeper","Stock Controller","Receiving Officer"],"actions":["Request replenishment","Receive purchased items","Record stock-in / stock-out","Transfer, return or write-off stock","Count stock and record variance"],"kpis":["Inventory value","Stockouts","Shrinkage","Low stock","Department consumption"],"tools":[{"label":"Inventory Register","detail":"Review live quantities, values and reorder status.","icon":"inventory","route":"inventory"},{"label":"New Request","detail":"Request replenishment or required supplies.","icon":"requests","action":"request"},{"label":"Store Catalogue","detail":"Browse stock, equipment and store tools.","icon":"box","route":"catalog"},{"label":"Assets","detail":"Review equipment held by the unit.","icon":"assets","route":"assets"}]}),
    ({"human", "hr", "people"}, {"title":"Human Resources","icon":"users","description":"Manage staff-related operating costs, issued resources, requests and people accountability.","roles":["HR Manager","HR Officer","Payroll / People Operations Officer"],"actions":["Create staff-related requests","Track payroll inputs","Record claims and advances","Assign staff assets","Track HR operating costs"],"kpis":["Payroll cost","Claims","Headcount cost","Advances","HR budget"],"tools":[{"label":"Staff Requests","detail":"Raise recruitment, welfare, training or office requests.","icon":"requests","action":"request"},{"label":"HR Catalogue","detail":"Browse HR devices, records, forms and welfare items.","icon":"users","route":"catalog"},{"label":"Assigned Assets","detail":"Review accountable staff-issued equipment.","icon":"assets","route":"assets"},{"label":"Reports","detail":"Review HR operating activity.","icon":"reports","route":"reports"}]}),
    ({"sales", "revenue", "admission", "front office", "customer"}, {"title":"Sales & Revenue Operations","icon":"finance","description":"Track revenue-facing activity, collections, receivables and approved customer-facing costs.","roles":["Manager","Sales / Revenue Officer","Cashier / Collector","Customer Officer"],"actions":["Record revenue","Raise invoices","Record collections","Track receivables","Log discounts/refunds for approval"],"kpis":["Revenue","Collections","Receivables","Conversion","Refunds"],"tools":[{"label":"Revenue / Finance","detail":"Open authorized financial records.","icon":"finance","route":"finance"},{"label":"Operating Requests","detail":"Request customer-service or sales resources.","icon":"requests","action":"request"},{"label":"Department Catalogue","detail":"Browse devices, service supplies and promotional items.","icon":"media","route":"catalog"},{"label":"Reports","detail":"Review revenue-facing performance records.","icon":"reports","route":"reports"}]}),
    ({"ict", "technology", "software", "cyber", "infrastructure"}, {"title":"ICT & Technology","icon":"device","description":"Control technology assets, subscriptions, repairs, infrastructure purchases and assigned devices.","roles":["ICT Manager","System Administrator","Developer / Engineer","IT Support Officer","Network Officer"],"actions":["Request devices, software or services","Track subscriptions and renewals","Assign technology assets","Record repairs and replacements","Track infrastructure cost"],"kpis":["Technology spend","Asset assignment","Renewals","Downtime cost","Budget usage"],"tools":[{"label":"Technology Catalogue","detail":"Computers, networking, cables, tools, printers and software.","icon":"device","route":"catalog"},{"label":"Request Equipment","detail":"Request laptops, accessories, services or subscriptions.","icon":"requests","action":"request"},{"label":"Technology Assets","detail":"Review accountable equipment records.","icon":"assets","route":"assets"},{"label":"Inventory","detail":"Review consumables and spare stock where permitted.","icon":"inventory","route":"inventory"}]}),
    ({"maintenance", "engineering", "mechanic", "workshop", "biomedical"}, {"title":"Maintenance & Engineering","icon":"tool","description":"Track repairs, spares, tools, equipment costs and accountable maintenance work.","roles":["Maintenance Manager","Engineer / Technician","Mechanic","Facility Officer"],"actions":["Create repair/work requests","Request spare parts","Record maintenance cost","Track tools and assets","Confirm work completion"],"kpis":["Maintenance cost","Downtime","Repeat faults","Spare-parts usage","Work-order completion"],"tools":[{"label":"Tools & Spares Catalogue","detail":"Browse tools, electrical, mechanical and safety items.","icon":"tool","route":"catalog"},{"label":"Repair / Parts Request","detail":"Request materials, spares or contractor services.","icon":"requests","action":"request"},{"label":"Equipment Assets","detail":"Review accountable machinery and tools.","icon":"assets","route":"assets"},{"label":"Inventory","detail":"Review spare parts and consumables.","icon":"inventory","route":"inventory"}]}),
    ({"transport", "logistics", "fleet", "dispatch"}, {"title":"Transport & Logistics","icon":"vehicle","description":"Track fleet resources, dispatch, fuel, repairs, movement and logistics cost.","roles":["Transport / Logistics Manager","Fleet Officer","Driver / Dispatcher","Mechanic"],"actions":["Record fuel / transport costs","Request repairs and parts","Track vehicle assets","Log dispatch / movement","Record transport income where applicable"],"kpis":["Fuel cost","Maintenance / vehicle","Route / job income","Vehicle downtime","Logistics spend"],"tools":[{"label":"Fleet Catalogue","detail":"Vehicles, parts, fuel-control items and operations records.","icon":"vehicle","route":"catalog"},{"label":"Transport Request","detail":"Request fuel, repair parts or logistics services.","icon":"requests","action":"request"},{"label":"Fleet Assets","detail":"Review accountable vehicles and equipment.","icon":"assets","route":"assets"},{"label":"Reports","detail":"Review transport activity and spend.","icon":"reports","route":"reports"}]}),
    ({"project", "operation", "program", "field"}, {"title":"Projects & Operations","icon":"briefcase","description":"Track project requests, field spending, advances, materials, funding and accountable operations.","roles":["Operations / Project Manager","Coordinator","Field Officer","Project Accountant"],"actions":["Create project requests","Track project income / funding","Record operational costs","Manage advances","Track project assets and materials"],"kpis":["Budget vs actual","Committed cost","Project margin / fund balance","Advance retirement","Cost / activity"],"tools":[{"label":"Project Request","detail":"Raise materials, services or field requirements.","icon":"requests","action":"request"},{"label":"Project Catalogue","detail":"Browse field equipment, materials and supplies.","icon":"briefcase","route":"catalog"},{"label":"Project Assets","detail":"Review equipment under project custody.","icon":"assets","route":"assets"},{"label":"Reports","detail":"Review project activity and costs.","icon":"reports","route":"reports"}]}),
    ({"laboratory", "pharmacy", "nursing", "medical", "clinical", "radiology"}, {"title":"Clinical / Medical Operations","icon":"medical","description":"Track medical/laboratory supplies, controlled stock, equipment, service costs and revenue where applicable.","roles":["Department Manager","Professional Officer","Technician / Assistant"],"actions":["Record department revenue where applicable","Request consumables, reagents or drugs","Track batch / expiry stock","Record usage and wastage","Track equipment / service costs"],"kpis":["Revenue","Cost of service","Inventory value","Expiry / wastage","Gross margin"],"tools":[{"label":"Clinical Catalogue","detail":"Browse department-specific equipment and consumables.","icon":"medical","route":"catalog"},{"label":"Supply Request","detail":"Request consumables, reagents, drugs or equipment.","icon":"requests","action":"request"},{"label":"Clinical Inventory","detail":"Review stock quantities and reorder exposure.","icon":"inventory","route":"inventory"},{"label":"Equipment","detail":"Review accountable medical/lab assets.","icon":"assets","route":"assets"}]}),
    ({"academic", "classroom", "library"}, {"title":"Academic Operations","icon":"document","description":"Track teaching resources, academic supplies, equipment and accountable departmental spending.","roles":["Academic Head","Teacher / Officer","Examination / Registry Officer","Librarian"],"actions":["Request books, materials or services","Record billable fees where applicable","Track teaching supplies","Monitor academic operating cost","Attach invoices and receipts"],"kpis":["Fees / revenue","Material consumption","Cost per activity","Budget usage","Evidence compliance"],"tools":[{"label":"Academic Catalogue","detail":"Browse books, classroom equipment and learning supplies.","icon":"document","route":"catalog"},{"label":"Materials Request","detail":"Request teaching or examination resources.","icon":"requests","action":"request"},{"label":"Academic Assets","detail":"Review accountable teaching equipment.","icon":"assets","route":"assets"},{"label":"Reports","detail":"Review academic operating records.","icon":"reports","route":"reports"}]}),
    ({"housekeeping", "laundry"}, {"title":"Housekeeping & Laundry","icon":"cleaning","description":"Control linen, cleaning supplies, amenities, equipment and consumption-related costs.","roles":["Executive Housekeeper","Supervisor","Room / Laundry Attendant"],"actions":["Request linen, amenities or chemicals","Record stock consumption","Track laundry-related income","Report damaged or missing items","Track housekeeping operating cost"],"kpis":["Cost per occupied room","Linen loss","Amenity usage","Laundry income","Stock variance"],"tools":[{"label":"Housekeeping Catalogue","detail":"Browse linen, amenities, chemicals and equipment.","icon":"cleaning","route":"catalog"},{"label":"Supply Request","detail":"Request linen, cleaning or guest supplies.","icon":"requests","action":"request"},{"label":"Stock","detail":"Review supplies and quantities.","icon":"inventory","route":"inventory"},{"label":"Assets","detail":"Review housekeeping equipment.","icon":"assets","route":"assets"}]}),
    ({"kitchen", "food production", "food & beverage", "restaurant", "culinary"}, {"title":"Food & Beverage Operations","icon":"food","description":"Track ingredients, service inventory, kitchen equipment, wastage and operating margin.","roles":["F&B / Kitchen Manager","Chef / Production Lead","Store / Service Officer"],"actions":["Request ingredients and supplies","Record food/service revenue","Track ingredient consumption","Record wastage / spoilage","Track outlet cost and margin"],"kpis":["Sales","Food cost %","Gross margin","Wastage","Stock variance"],"tools":[{"label":"Food & Kitchen Catalogue","detail":"Browse ingredients, equipment and service ware.","icon":"food","route":"catalog"},{"label":"Ingredient Request","detail":"Request food, packaging or service supplies.","icon":"requests","action":"request"},{"label":"Kitchen Inventory","detail":"Review ingredient and supply stock.","icon":"inventory","route":"inventory"},{"label":"Equipment","detail":"Review kitchen equipment assets.","icon":"assets","route":"assets"}]}),
    ({"production", "factory", "packaging"}, {"title":"Production Operations","icon":"box","description":"Track production materials, line equipment, output-related supplies, waste and operating cost.","roles":["Production Manager","Shift Supervisor","Machine Operator"],"actions":["Record production output","Request raw materials and consumables","Track material consumption","Record scrap / rework","Track production operating cost"],"kpis":["Output","Yield","Unit cost","Waste","Downtime"],"tools":[{"label":"Production Catalogue","detail":"Browse machinery, raw materials, packaging and PPE.","icon":"box","route":"catalog"},{"label":"Material Request","detail":"Request production materials or consumables.","icon":"requests","action":"request"},{"label":"Production Inventory","detail":"Review available materials and stock.","icon":"inventory","route":"inventory"},{"label":"Equipment","detail":"Review line and production assets.","icon":"assets","route":"assets"}]}),
    ({"quality", "qa", "qc", "health & safety", "hse"}, {"title":"Quality & Safety","icon":"safety","description":"Track inspection supplies, safety equipment, quality evidence, incidents and compliance costs.","roles":["Quality / HSE Manager","Analyst / Inspector","Safety Officer"],"actions":["Request testing or safety supplies","Track inspection materials","Record rejection / incidents","Attach quality evidence","Track compliance-related cost"],"kpis":["Reject rate","Quality loss","Safety cost","Incident cost","Compliance"],"tools":[{"label":"Quality & Safety Catalogue","detail":"Browse testing, calibration and PPE items.","icon":"safety","route":"catalog"},{"label":"Supply Request","detail":"Request testing, safety or compliance resources.","icon":"requests","action":"request"},{"label":"Controlled Assets","detail":"Review accountable inspection equipment.","icon":"assets","route":"assets"},{"label":"Reports","detail":"Review quality and compliance activity.","icon":"reports","route":"reports"}]}),
    ({"security", "loss prevention"}, {"title":"Security Operations","icon":"lock","description":"Track security equipment, access-control resources, incidents and accountable custody.","roles":["Security Manager","Supervisor","Guard / CCTV Officer"],"actions":["Request security supplies or services","Track issued equipment","Record incident-linked expenses","Log asset issue / return","Track contract and renewal costs"],"kpis":["Incident loss","Security spend","Asset custody","Vendor cost","Control exceptions"],"tools":[{"label":"Security Catalogue","detail":"Browse CCTV, access-control, radios and safety items.","icon":"lock","route":"catalog"},{"label":"Security Request","detail":"Request equipment, uniforms or services.","icon":"requests","action":"request"},{"label":"Issued Assets","detail":"Review accountable security equipment.","icon":"assets","route":"assets"},{"label":"Reports","detail":"Review security-related activity.","icon":"reports","route":"reports"}]}),
    ({"marketing", "public relations", "communications", "partnership", "business development"}, {"title":"Marketing & Business Development","icon":"media","description":"Track campaigns, promotional assets, events, lead-generating spend and supporting evidence.","roles":["Marketing / Communications Manager","PR / Content Officer","Business Development Officer"],"actions":["Create campaign requests","Record campaign/event income","Track advertising spend","Manage promotional inventory/assets","Attach campaign/vendor evidence"],"kpis":["Campaign spend","Revenue influence","ROI","Cost per lead","Budget usage"],"tools":[{"label":"Marketing Catalogue","detail":"Browse media equipment, print items and event materials.","icon":"media","route":"catalog"},{"label":"Campaign Request","detail":"Request advertising, events or production resources.","icon":"requests","action":"request"},{"label":"Marketing Assets","detail":"Review cameras, event gear and promotional equipment.","icon":"assets","route":"assets"},{"label":"Reports","detail":"Review campaign-related business activity.","icon":"reports","route":"reports"}]}),
]


def department_profile(name):
    text = (name or "").lower()
    for keywords, profile in PROFILES:
        if any(keyword in text for keyword in keywords): return {**DEFAULT, **profile}
    return DEFAULT.copy()


def role_focus(position, department_name=""):
    """Describe the staff member's practical job focus without changing security permissions."""
    text = f"{position or ''} {department_name or ''}".lower(); title = position or "Department Staff"
    if any(word in text for word in ["manager", "head", "director", "lead", "supervisor", "matron", "chief"]): return {"title": title, "badge": "Oversight", "icon": "analytics", "responsibilities": ["Monitor department activity and exceptions", "Coordinate accountable requests and records", "Review stock/assets within assigned duties", "Track departmental KPIs and evidence"]}
    if any(word in text for word in ["storekeeper", "inventory", "stock controller", "warehouse"]): return {"title": title, "badge": "Stock Custody", "icon": "inventory", "responsibilities": ["Receive and count items", "Maintain stock quantities and locations", "Record issue/return/transfer activity", "Flag low stock and discrepancies"]}
    if any(word in text for word in ["accountant", "cashier", "finance", "billing", "treasury", "auditor"]): return {"title": title, "badge": "Financial Control", "icon": "finance", "responsibilities": ["Maintain authorized financial records", "Reconcile evidence and balances", "Track income/expense accountability", "Produce finance-ready reports"]}
    if any(word in text for word in ["buyer", "procurement", "purchasing"]): return {"title": title, "badge": "Sourcing", "icon": "cart", "responsibilities": ["Turn approved needs into sourcing activity", "Compare suppliers and quotations", "Track purchase commitments", "Coordinate delivery evidence"]}
    if any(word in text for word in ["developer", "ict", "it ", "support", "network", "system administrator", "engineer", "technician"]): return {"title": title, "badge": "Technical", "icon": "device", "responsibilities": ["Track accountable equipment and tools", "Request technical items/services", "Record repairs, renewals and replacements", "Maintain evidence for assigned resources"]}
    return {"title": title, "badge": "Department Role", "icon": department_profile(department_name).get("icon", "briefcase"), "responsibilities": department_profile(department_name).get("actions", DEFAULT["actions"])[:4]}
