# SERVICE: SAGE Organization Catalog
# Canonical organization + individual-business categories used during owner onboarding. Lists intentionally favour common Nigerian/African operating structures while remaining globally usable.

BUSINESS_TYPES = [
    {"key":"school","label":"School / Educational Institution","group":"Education & Social","departments":["Administration","Finance & Accounts","Human Resources","Academic / Classroom","Examinations & Assessment","CBT / Computer-Based Test Centre","ICT / Computer Laboratory","Science Laboratory","Library","Admissions / Enrolment","Student Affairs / Guidance & Counselling","Boarding / Hostel","Kitchen / Catering","Uniform / Tailoring / Garment Production","School Clinic / Sick Bay","Procurement","Stores / Inventory","Maintenance / Works","Transport","Security","Marketing / PR / Communications","Sports / Physical Education","Events / Hall Management","Alumni / Parent Relations","Quality Assurance / School Compliance","Islamiyyah / Religious Studies","Tahfeez / Memorisation","Creche / Early Years","Cleaning / Sanitation"]},
    {"key":"healthcare","label":"Hospital / Clinic / Diagnostic Centre","group":"Health & Care","departments":["Administration","Finance & Accounts","Human Resources","Medical / Doctors / Consultation","Nursing","Medical Laboratory","Pharmacy","Radiology / Imaging","Theatre / Surgery","Emergency / Accident & Emergency","Dental","Physiotherapy / Rehabilitation","Dialysis","Optometry / Eye Clinic","Front Desk / Customer Care","Health Information / Medical Records","Insurance / HMO","Public Health / Outreach","Procurement","Stores / Medical Store","ICT / IT","Maintenance / Biomedical","Housekeeping / Sanitation","Security","Marketing / Business Development","Quality Assurance / Compliance","Mortuary","Ambulance / Transport"]},
    {"key":"hospitality","label":"Hotel / Hospitality Company","group":"Hospitality & Lifestyle","departments":["Front Office / Reception","Reservations","Housekeeping","Food & Beverage Service","Kitchen / Culinary","Restaurant / Bar","Banquet / Events","Laundry","Guest Relations / Concierge","Finance & Accounts","Human Resources","Procurement","Stores / Inventory","Maintenance / Engineering","Security","Sales / Marketing / Events","ICT / IT","Spa / Wellness","Gym / Recreation","Pool Operations","Transport / Airport Shuttle","Quality Assurance","Conference / Hall Management","Revenue Management"]},
    {"key":"manufacturing","label":"Manufacturing Company / Factory","group":"Industry & Production","departments":["Production","Quality Control / Quality Assurance","Engineering / Maintenance","Research & Development","Product Design","Raw Materials","Packaging","Procurement","Warehouse / Stores","Finance & Accounts","Human Resources","Sales","Marketing","Logistics / Distribution","Health, Safety & Environment (HSE)","ICT / IT","Utilities / Power","Machine Shop / Fabrication","Planning / Production Control","Supply Chain","Customer Service","Compliance / Regulatory","Waste Management","Security","Administration"]},
    {"key":"retail","label":"Retail / Supermarket / Shopping Company","group":"Trade & Commerce","departments":["Sales Floor","Cashier / POS","Procurement / Buying","Inventory Control","Warehouse / Back Store","Receiving / Goods In","Finance & Accounts","Human Resources","Customer Service","Marketing / Visual Merchandising","Logistics / Delivery","Security / Loss Prevention","ICT / IT","E-commerce / Online Orders","Returns / After-Sales","Bakery / Fresh Food","Butchery / Meat Section","Cold Room / Frozen Foods","Pharmacy / Health Corner","Fashion / Clothing","Home & Electronics","Wholesale / Corporate Sales","Administration"]},
    {"key":"construction","label":"Construction / Engineering Company","group":"Built Environment","departments":["Projects / Project Management","Civil / Structural Engineering","Mechanical Engineering","Electrical Engineering","Quantity Surveying / Cost Control","Surveying / Geomatics","Architecture / Design","Site Operations / Civil Works","Plant / Equipment","Procurement","Stores / Warehouse","Health, Safety & Environment (HSE)","Logistics","Finance & Accounts","Human Resources / Administration","ICT / IT","Contracts / Tendering","Planning / Scheduling","Quality Assurance / Quality Control","Materials Laboratory","Fabrication / Workshop","Facilities Management","Legal / Compliance","Business Development"]},
    {"key":"logistics","label":"Logistics / Transport Company","group":"Mobility & Logistics","departments":["Operations / Control Room","Fleet Management","Dispatch / Last Mile","Warehouse / Fulfilment","Freight Forwarding","Haulage / Long Distance","Courier Operations","Route Planning","Maintenance / Workshop","Procurement","Finance & Accounts","Human Resources","Customer Service","ICT / IT","Sales / Marketing","Health & Safety","Fuel Management","Drivers / Riders","Tracking / Telematics","Customs / Clearing","Cold Chain Logistics","Security","Administration","Quality / Compliance"]},
    {"key":"restaurant","label":"Restaurant / Fast Food / Catering Company","group":"Food & Hospitality","departments":["Kitchen","Food Production / Bakery / Prep","Front of House / Customer Service","Sales / POS","Procurement","Stores / Inventory","Delivery / Dispatch","Quality Control / Food Safety","Finance & Accounts","Human Resources","Marketing","Maintenance","Catering / Outdoor Events","Bakery / Pastry","Bar / Beverages","Cold Room / Storage","Cleaning / Stewarding","Menu / Product Development","Central Production Kitchen","Security","Administration"]},
    {"key":"technology","label":"Technology / Software Company","group":"Technology & Digital","departments":["Software Development / Engineering","UI / UX Design","Product Management","ICT / Infrastructure / DevOps","Quality Assurance / Testing","Cybersecurity","Data / AI / Analytics","Cloud / Platform Engineering","Mobile Development","Web Development","Hardware / IoT","Research & Development","Project / Delivery Management","Sales","Marketing / Growth","Customer Support / Success","Implementation / Onboarding","Training / Academy","Finance & Accounts","Human Resources / People Operations","Administration / Workplace","Procurement","Legal / Compliance","Partnerships","Content / Media"]},
    {"key":"ngo","label":"NGO / Foundation / Non-Profit Organization","group":"Education & Social","departments":["Administration","Finance & Accounts","Human Resources","Programs","Projects / Implementation","Monitoring, Evaluation, Accountability & Learning (MEAL/M&E)","Procurement","Logistics / Fleet","Communications / Advocacy","Partnerships / Fundraising","ICT / IT","Field Operations","Grants / Compliance","Research / Learning","Safeguarding / Protection","Health Programs","Education Programs","Livelihoods / Economic Empowerment","Community Engagement","Warehouse / Relief Items","Security","Legal / Governance","Volunteer Management","Donor Relations"]},
    {"key":"agriculture","label":"Agriculture / Farm / Agro-Processing Company","group":"Agriculture & Natural Resources","departments":["Farm Operations","Crop Production","Livestock","Poultry","Fishery / Aquaculture","Agronomy / Extension","Veterinary / Animal Health","Irrigation / Water Management","Feed Mill / Feed Production","Agro-Processing / Production","Quality Control / Food Safety","Cold Store / Produce Storage","Procurement","Stores / Inputs Warehouse","Plant / Equipment / Maintenance","Transport / Farm Logistics","Sales / Offtake","Finance & Accounts","Human Resources","Administration","Health, Safety & Environment (HSE)","Security"]},
    {"key":"real_estate","label":"Real Estate / Property Development Company","group":"Built Environment","departments":["Property Acquisition","Property Development / Projects","Estate / Facility Management","Property Management","Sales / Leasing","Valuation","Surveying / Geomatics","Architecture / Design","Construction / Site Operations","Tenant / Client Relations","Legal / Documentation","Finance & Accounts","Human Resources","Procurement","Maintenance / Technical Services","Security","Marketing / Business Development","ICT / IT","Cleaning / Estate Services","Administration"]},
    {"key":"financial_services","label":"Banking / Microfinance / Fintech / Financial Services","group":"Finance & Professional","departments":["Branch Operations","Teller / Cash Operations","Customer Service","Credit / Loans","Risk Management","Compliance / AML / KYC","Internal Audit","Treasury","Finance & Accounts","Collections / Recovery","Digital Banking / Fintech Operations","Cards / Payments","Agent Banking / Agency Network","Product Management","ICT / Core Banking","Cybersecurity","Sales / Relationship Management","Marketing","Legal / Company Secretariat","Human Resources","Administration / Operations"]},
    {"key":"professional_services","label":"Professional Services / Consulting / Legal / Accounting Firm","group":"Finance & Professional","departments":["Client Services","Consulting / Advisory","Legal Services","Accounting / Bookkeeping","Tax","Audit / Assurance","Business Advisory","Project Management","Research","Data / Analytics","Training / Learning","Business Development","Finance & Accounts","Human Resources","Administration","ICT / IT","Procurement","Records / Document Control","Compliance / Quality","Customer Support"]},
    {"key":"media_creative","label":"Media / Creative / Advertising / Production Company","group":"Media & Creative","departments":["Content / Production","Editorial / Newsroom","Studio Operations","Photography","Videography / Cinematography","Audio / Sound","Graphic Design / Branding","Animation / Motion Graphics","Post-Production / Editing","Digital / Social Media","Advertising / Campaigns","Client Service / Accounts","Sales / Business Development","Events / Activations","Equipment / Technical","Marketing","Finance & Accounts","Human Resources","ICT / IT","Administration"]},
    {"key":"fashion_garment","label":"Fashion / Garment / Textile Company","group":"Trade & Commerce","departments":["Fashion Design","Tailoring / Garment Production","Cutting / Pattern Making","Embroidery / Branding","Quality Control","Fabric / Raw Materials Store","Procurement","Warehouse / Finished Goods","Retail / Showroom","Wholesale / Corporate Sales","E-commerce / Online Orders","Marketing / Content","Customer Service","Logistics / Delivery","Machine / Equipment Maintenance","Finance & Accounts","Human Resources","Administration","Security"]},
    {"key":"beauty_wellness","label":"Beauty / Salon / Spa / Wellness Company","group":"Hospitality & Lifestyle","departments":["Salon / Hair Services","Barbing / Grooming","Spa / Massage","Nails / Manicure / Pedicure","Makeup / Beauty Services","Skincare / Aesthetics","Reception / Front Desk","Customer Service","Retail / Product Sales","Procurement","Stores / Inventory","Laundry / Sanitation","Training / Academy","Marketing / Social Media","Maintenance","Finance & Accounts","Human Resources","Administration"]},
    {"key":"wholesale_distribution","label":"Wholesale / Distribution / Trading Company","group":"Trade & Commerce","departments":["Procurement / Sourcing","Wholesale Sales","Key Accounts / Corporate Sales","Warehouse / Distribution Centre","Receiving / Goods In","Inventory Control","Dispatch / Delivery","Route Sales / Field Sales","Logistics / Fleet","Credit Control","Finance & Accounts","Customer Service","Marketing / Trade Marketing","E-commerce / Order Desk","ICT / IT","Human Resources","Security / Loss Prevention","Administration"]},
    {"key":"energy_power","label":"Energy / Solar / Power Company","group":"Energy & Infrastructure","departments":["Project Development","Solar / Renewable Energy","Electrical Engineering","Installation / Field Services","Operations & Maintenance","Power Systems / Utilities","Metering / Energy Management","Energy Audit / Technical Advisory","Procurement","Warehouse / Stores","Health, Safety & Environment (HSE)","Quality Assurance","Sales / Business Development","Customer Service","Finance & Accounts","Human Resources","Logistics","ICT / IT","Regulatory / Compliance","Administration"]},
    {"key":"oil_gas","label":"Oil / Gas / Petroleum Services Company","group":"Energy & Infrastructure","departments":["Field / Technical Operations","Upstream Services","Downstream Operations","Depot / Terminal Operations","Retail Station Operations","Engineering / Projects","Maintenance / Workshop","Health, Safety & Environment (HSE)","Quality / Laboratory","Procurement","Supply Chain / Stores","Logistics / Haulage","Fleet / Tanker Operations","Commercial / Sales","Marketing","Finance & Accounts","Human Resources","Security","Regulatory / Compliance","ICT / IT","Administration"]},
    {"key":"telecom","label":"Telecommunications / ISP / Communications Company","group":"Technology & Digital","departments":["Network Operations Centre (NOC)","Network Engineering","RF / Transmission","Fiber / Broadband","Tower / Site Operations","Field Services","ICT / IT","Cybersecurity","Customer Care","Retail / Service Centres","Enterprise Sales","Consumer Sales","Billing / Revenue Assurance","Product Management","Marketing","Procurement","Warehouse / Spares","Finance & Accounts","Human Resources","Regulatory / Compliance","Administration"]},
    {"key":"religious","label":"Religious / Faith-Based Organization","group":"Education & Social","departments":["Administration","Finance & Accounts","Pastoral / Clergy / Leadership","Programs / Ministries","Education / Religious Studies","Media / Communications","Music / Worship","Events / Protocol","Welfare / Charity","Youth Programs","Children Programs","Outreach / Missions","Counselling","Facilities / Maintenance","Security","Procurement","Stores / Inventory","Transport","ICT / IT","Volunteers / Human Resources"]},
    {"key":"travel_tourism","label":"Travel / Tourism / Ticketing Company","group":"Hospitality & Lifestyle","departments":["Reservations / Ticketing","Tour Operations","Visa / Documentation","Corporate Travel","Customer Service","Sales","Marketing / Partnerships","Transport / Transfers","Tour Guides","Accommodation Partnerships","Events / Destination Management","Finance & Accounts","Human Resources","ICT / Booking Systems","Procurement","Quality Assurance","Security / Travel Risk","Administration"]},
    {"key":"facilities_cleaning","label":"Facilities / Cleaning / Property Management Company","group":"Built Environment","departments":["Facility Management","Cleaning / Housekeeping","Maintenance / Technical Services","Landscaping / Grounds","Pest Control / Fumigation","Waste Management","Security","Front Desk / Concierge","Procurement","Stores / Consumables","Fleet / Transport","Health, Safety & Environment (HSE)","Quality Assurance","Customer Service","Contracts / Client Management","Sales / Business Development","Finance & Accounts","Human Resources","Administration"]},
    {"key":"printing_publishing","label":"Printing / Publishing / Branding Company","group":"Media & Creative","departments":["Prepress / Graphic Design","Printing / Press Operations","Binding / Finishing","Publishing / Editorial","Copywriting / Content","Branding / Large Format","Production Planning","Quality Control","Procurement","Paper / Materials Store","Warehouse / Finished Goods","Sales / Business Development","Marketing","Customer Service","Delivery / Logistics","Equipment Maintenance","Finance & Accounts","Human Resources","ICT / IT","Administration"]},
    {"key":"events_entertainment","label":"Events / Entertainment / Production Company","group":"Media & Creative","departments":["Event Planning / Production","Client Service","Creative / Design","Decoration / Styling","Rentals / Equipment","Stage / Lighting","Sound / DJ / Technical","Photography / Videography","Entertainment / Talent","Catering / Hospitality","Logistics / Transport","Venue / Facility Operations","Ticketing / Registration","Marketing / Publicity","Procurement","Inventory / Stores","Finance & Accounts","Human Resources","Security / Crowd Control","Administration"]},
    {"key":"security_services","label":"Security / Guarding / Protection Services Company","group":"Services & Operations","departments":["Operations / Deployment","Guarding Services","Patrol / Response","Control Room / Command Centre","CCTV / Surveillance","Access Control","Investigation / Intelligence","Training / Academy","Recruitment / Vetting","Fleet / Patrol Vehicles","Equipment / Armoury Control","Client Service","Sales / Business Development","Finance & Accounts","Human Resources","Compliance / Licensing","Health & Safety","ICT / IT","Administration"]},
    {"key":"automotive","label":"Automotive / Mechanic / Car Dealership Company","group":"Mobility & Logistics","departments":["Workshop / Service Centre","Mechanical Repairs","Auto Electrical / Electronics","Diagnostics","Bodywork / Panel Beating","Paint / Refinishing","Spare Parts","Tyres / Batteries","Vehicle Sales / Dealership","Service Reception","Customer Care","Procurement","Stores / Parts Warehouse","Quality Control","Towing / Recovery","Fleet / Test Drive","Finance & Accounts","Human Resources","Marketing / Sales","Administration"]},
    {"key":"mining_quarry","label":"Mining / Quarry / Solid Minerals Company","group":"Agriculture & Natural Resources","departments":["Mining / Quarry Operations","Geology / Exploration","Surveying","Drilling / Blasting","Crushing / Processing","Plant / Heavy Equipment","Engineering / Maintenance","Health, Safety & Environment (HSE)","Environment / Sustainability","Quality / Laboratory","Procurement","Stores / Warehouse","Logistics / Haulage","Weighbridge / Dispatch","Security","Finance & Accounts","Human Resources","Regulatory / Compliance","Community Relations","Administration"]},
    {"key":"other","label":"Other / Custom Organization","group":"Other","departments":["Administration","Finance & Accounts","Human Resources","Procurement","Stores / Inventory","Operations","ICT / IT","Sales","Marketing / Communications","Customer Service","Logistics / Transport","Maintenance","Security","Quality / Compliance","Projects","Production","Research & Development","Legal","Training","Facilities / Estate"]},
]
BUSINESS_TYPE_MAP = {item["key"]: item for item in BUSINESS_TYPES}


def suggested_departments(business_type_key): return list(BUSINESS_TYPE_MAP.get(business_type_key, BUSINESS_TYPE_MAP["other"])["departments"])

# ==========================================================
# INDIVIDUAL / ENTREPRENEUR BUSINESS TYPES — 30 common owner-operated categories.
# Each maps to the nearest organization catalogue so lean businesses inherit useful stock/assets/finance defaults without forcing a department hierarchy.
# ==========================================================
INDIVIDUAL_BUSINESS_TYPES = [
    {"key":"retail_shop","label":"Retail Shop / Mini Mart / Boutique","group":"Trade & Retail","catalog_key":"retail","primary_department":"Sales Floor"},
    {"key":"wholesale_trading","label":"Wholesale / Trading / Distribution","group":"Trade & Retail","catalog_key":"wholesale_distribution","primary_department":"Wholesale Sales"},
    {"key":"ecommerce","label":"Online Store / E-commerce Business","group":"Trade & Retail","catalog_key":"retail","primary_department":"E-commerce / Online Orders"},
    {"key":"pos_agent_banking","label":"POS / Mobile Money / Agent Banking","group":"Money & Professional","catalog_key":"financial_services","primary_department":"Agent Banking / Agency Network"},
    {"key":"pastries_bakery","label":"Pastries / Bakery / Cake Business","group":"Food & Hospitality","catalog_key":"restaurant","primary_department":"Bakery / Pastry"},
    {"key":"chef_catering","label":"Chef / Catering / Food Vendor","group":"Food & Hospitality","catalog_key":"restaurant","primary_department":"Catering / Outdoor Events"},
    {"key":"restaurant_food","label":"Restaurant / Fast Food / Small Chops","group":"Food & Hospitality","catalog_key":"restaurant","primary_department":"Kitchen"},
    {"key":"photography","label":"Photography Studio / Photographer","group":"Creative & Media","catalog_key":"media_creative","primary_department":"Photography"},
    {"key":"videography_content","label":"Videography / Content Creation","group":"Creative & Media","catalog_key":"media_creative","primary_department":"Videography / Cinematography"},
    {"key":"digital_marketing","label":"Digital Marketing / Advertising","group":"Creative & Media","catalog_key":"media_creative","primary_department":"Advertising / Campaigns"},
    {"key":"graphic_design","label":"Graphic Design / Branding / Printing","group":"Creative & Media","catalog_key":"printing_publishing","primary_department":"Prepress / Graphic Design"},
    {"key":"fashion","label":"Fashion / Tailoring / Clothing Business","group":"Lifestyle & Beauty","catalog_key":"fashion_garment","primary_department":"Tailoring / Garment Production"},
    {"key":"beauty","label":"Beauty Salon / Spa / Nails","group":"Lifestyle & Beauty","catalog_key":"beauty_wellness","primary_department":"Salon / Hair Services"},
    {"key":"barber","label":"Barbing / Grooming Business","group":"Lifestyle & Beauty","catalog_key":"beauty_wellness","primary_department":"Barbing / Grooming"},
    {"key":"makeup","label":"Makeup Artist / Beauty Services","group":"Lifestyle & Beauty","catalog_key":"beauty_wellness","primary_department":"Makeup / Beauty Services"},
    {"key":"event_planning","label":"Events Planning / Decoration / Rentals","group":"Events & Entertainment","catalog_key":"events_entertainment","primary_department":"Event Planning / Production"},
    {"key":"model_talent","label":"Model / Talent / Creative Professional","group":"Events & Entertainment","catalog_key":"events_entertainment","primary_department":"Entertainment / Talent"},
    {"key":"transport","label":"Transport / Taxi / Ride Service","group":"Transport & Field Services","catalog_key":"logistics","primary_department":"Operations / Control Room"},
    {"key":"dispatch_courier","label":"Dispatch / Courier / Delivery Business","group":"Transport & Field Services","catalog_key":"logistics","primary_department":"Dispatch / Last Mile"},
    {"key":"construction_artisan","label":"Construction / Artisan / Handyman Business","group":"Transport & Field Services","catalog_key":"construction","primary_department":"Site Operations / Civil Works"},
    {"key":"agriculture","label":"Agriculture / Farm / Agro-business","group":"Agriculture & Wellness","catalog_key":"agriculture","primary_department":"Farm Operations"},
    {"key":"poultry_livestock","label":"Poultry / Livestock / Fishery Business","group":"Agriculture & Wellness","catalog_key":"agriculture","primary_department":"Livestock"},
    {"key":"health_wellness","label":"Health / Wellness Practice","group":"Agriculture & Wellness","catalog_key":"healthcare","primary_department":"Administration"},
    {"key":"fitness","label":"Fitness / Gym / Personal Trainer","group":"Agriculture & Wellness","catalog_key":"beauty_wellness","primary_department":"Training / Academy"},
    {"key":"real_estate_agent","label":"Real Estate / Property Agent","group":"Professional & Digital","catalog_key":"real_estate","primary_department":"Sales / Leasing"},
    {"key":"consulting","label":"Consulting / Professional Services","group":"Professional & Digital","catalog_key":"professional_services","primary_department":"Consulting / Advisory"},
    {"key":"training_tutoring","label":"Coaching / Training / Tutoring","group":"Professional & Digital","catalog_key":"professional_services","primary_department":"Training / Learning"},
    {"key":"technology","label":"Technology / Software / Digital Services","group":"Professional & Digital","catalog_key":"technology","primary_department":"Software Development / Engineering"},
    {"key":"freelance","label":"Freelance / Remote Professional","group":"Professional & Digital","catalog_key":"professional_services","primary_department":"Client Services"},
    {"key":"other","label":"Other / Custom Individual Business","group":"Other","catalog_key":"other","primary_department":"Administration"},
]
INDIVIDUAL_BUSINESS_TYPE_MAP = {item["key"]: item for item in INDIVIDUAL_BUSINESS_TYPES}


LEGACY_INDIVIDUAL_TYPE_ALIASES = {"food":"restaurant_food", "creative":"photography", "construction":"construction_artisan", "health":"health_wellness", "real_estate":"real_estate_agent"}
def individual_business_type(key):
    normalized = str(key or "").strip(); normalized = LEGACY_INDIVIDUAL_TYPE_ALIASES.get(normalized, normalized); return INDIVIDUAL_BUSINESS_TYPE_MAP.get(normalized, INDIVIDUAL_BUSINESS_TYPE_MAP["other"])
def canonical_business_for_individual(key):
    item = individual_business_type(key); catalog = BUSINESS_TYPE_MAP.get(item["catalog_key"], BUSINESS_TYPE_MAP["other"]); return {**item, "catalog_label": catalog["label"]}
